# Generated by Django 5.0.2 on 2024-02-11 19:30

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('color', colorfield.fields.ColorField(default='#0066FF', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('sortOrder', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.event')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vaccineStatus', models.CharField(choices=[('?', 'TBD'), ('R', 'DANGER'), ('O', 'RISK'), ('Y', 'OKAY'), ('G', 'OPTIMAL')], default='?', max_length=2)),
                ('radioNumber', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.event')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('callStart', models.DateTimeField(blank=True, null=True)),
                ('callEnd', models.DateTimeField(blank=True, null=True)),
                ('initialCode', models.CharField(blank=True, max_length=100, null=True)),
                ('revisedCode', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.event')),
                ('membersAttached', models.ManyToManyField(blank=True, null=True, to='roster.member')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('color', colorfield.fields.ColorField(default='#0066FF', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('sortOrder', models.IntegerField(default=0)),
                ('displayOnSidebar', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.event')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4)),
                ('color', colorfield.fields.ColorField(default='#0066FF', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('sortOrder', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.event')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('sortOrder', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.event')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='volumeRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.volumerole'),
        ),
    ]
