# Generated by Django 5.0.2 on 2024-02-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highVolumeMode',
            field=models.BooleanField(default=False),
        ),
    ]
