# Generated by Django 5.0.2 on 2024-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_event_highvolumemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='callKey',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='statusType',
            field=models.CharField(choices=[('A', 'Available'), ('X', 'AFK'), ('C', 'On a Call'), ('Y', 'TDY'), ('Z', 'Gone')], default='A', max_length=1),
        ),
    ]
