# Generated by Django 5.0.2 on 2024-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_alter_call_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='callKey',
            field=models.CharField(default='NEW', max_length=255),
        ),
    ]
