# Generated by Django 5.0.2 on 2024-02-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_call_callkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='statusType',
        ),
        migrations.AlterField(
            model_name='status',
            name='key',
            field=models.CharField(choices=[('A', 'Available'), ('X', 'AFK'), ('C', 'On a Call'), ('Y', 'TDY'), ('Z', 'Gone')], default='A', max_length=4),
        ),
    ]
