# Generated by Django 5.0.2 on 2024-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_remove_status_statustype_alter_status_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='showInColumns',
            field=models.BooleanField(default=False),
        ),
    ]
