# Generated by Django 5.0.2 on 2024-02-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_status_showincolumns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='showInColumns',
            new_name='hideFromColumns',
        ),
    ]
