# Generated by Django 5.0.2 on 2024-02-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_rename_showincolumns_status_hidefromcolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='key',
            field=models.CharField(choices=[('A', 'Available'), ('C', 'On a Call'), ('X', 'AFK'), ('Y', 'TDY'), ('Z', 'Gone')], default='A', max_length=4),
        ),
    ]
