# Generated by Django 5.0.2 on 2024-02-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_duty_default_status_default_alter_status_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.duty'),
        ),
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.rank'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.status'),
        ),
        migrations.AddField(
            model_name='rank',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
