# Generated by Django 5.0.2 on 2024-02-12 23:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_member_duty_member_rank_member_status_rank_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_key',
            field=models.UUIDField(default=uuid.UUID('5789cbb0-89c0-4a21-9ac2-e355cecc658d'), unique=True),
        ),
    ]
