# Generated by Django 5.0.2 on 2024-02-12 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_alter_event_public_key_accessright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='public_key',
        ),
        migrations.AddField(
            model_name='event',
            name='publicKey',
            field=models.UUIDField(default=uuid.UUID('f35f69a6-f60b-48de-8d2f-2b4e34befadc'), unique=True),
        ),
    ]
