# Generated by Django 5.0.2 on 2024-02-13 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_remove_event_public_key_event_publickey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='default',
            field=models.BooleanField(default=False, help_text='If checked, new members will be assigned this duty on creation.'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='key',
            field=models.CharField(help_text='Quick Key of the Duty for at-a-glance assignment', max_length=5),
        ),
        migrations.AlterField(
            model_name='duty',
            name='name',
            field=models.CharField(help_text='Name of the Duty', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='highVolumeMode',
            field=models.BooleanField(default=False, help_text='Enables Member Teaming and High Volume Roles for Rapid Response'),
        ),
        migrations.AlterField(
            model_name='event',
            name='key',
            field=models.SlugField(help_text='This will be the url key of the event and must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Name of the Event', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Supports Basic Markdown', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='publicKey',
            field=models.UUIDField(default=uuid.UUID('eac78520-62d0-4876-ac77-a0d8b0d7a42d'), unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='details',
            field=models.TextField(blank=True, help_text="Shows in the Information Line of the Member's status entry.", null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duty',
            field=models.ForeignKey(blank=True, help_text='Initial Duty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.duty'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(help_text='Name of the Member which will show on the board.', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='radioNumber',
            field=models.TextField(blank=True, help_text='Used for record keeping', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.ForeignKey(blank=True, help_text='Initial Rank', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.rank'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Initial Status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='vaccineStatus',
            field=models.CharField(choices=[('?', 'TBD'), ('R', 'DANGER'), ('O', 'RISK'), ('Y', 'OKAY'), ('G', 'OPTIMAL')], default='?', help_text='Used for Record Keeping', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='volumeRole',
            field=models.ForeignKey(blank=True, help_text='Assigned Role during High Volume Operations. This can be assigned later.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.volumerole'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='default',
            field=models.BooleanField(default=False, help_text='If checked, new members will be assigned this Rank on creation if not preassigned.'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='displayOnSidebar',
            field=models.BooleanField(default=True, help_text='If checked, a list of Members with this Rank will be displayed on the Sidebar of the Board.'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='key',
            field=models.CharField(help_text='Displays the Rank of the Member, typically used to distinguish different ranks of responders.', max_length=5),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(help_text='Full name of the Rank', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='default',
            field=models.BooleanField(default=False, help_text='If checked, new members will be assigned this status on creation.'),
        ),
        migrations.AlterField(
            model_name='status',
            name='hideFromColumns',
            field=models.BooleanField(default=False, help_text='If checked, it will show underneath the main columns in a larger section. Meant for storing users not active in tracking.'),
        ),
        migrations.AlterField(
            model_name='status',
            name='key',
            field=models.CharField(choices=[('A', 'Available'), ('C', 'On a Call'), ('X', 'AFK'), ('Y', 'TDY'), ('Z', 'Gone')], default='A', help_text='This grouping determines which column this section will fall under', max_length=4),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='Name of the Status Column', max_length=100),
        ),
        migrations.AlterField(
            model_name='volumerole',
            name='key',
            field=models.CharField(help_text="This will appear on the Member's Status Entry", max_length=100),
        ),
    ]
