# Generated by Django 5.0.2 on 2024-02-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_alter_duty_default_alter_duty_key_alter_duty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='publicKey',
        ),
    ]
