# Generated by Django 5.0.2 on 2024-05-25 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_servicekiosk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicekiosk',
            name='id',
        ),
        migrations.AddField(
            model_name='servicekiosk',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
