# Generated by Django 5.0.2 on 2024-05-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0017_remove_servicekiosk_id_servicekiosk_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.member')),
            ],
        ),
    ]
