# Generated by Django 5.0.2 on 2024-05-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0018_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.event'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.member'),
        ),
        migrations.AlterField(
            model_name='servicekiosk',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.event'),
        ),
    ]
