# Generated by Django 5.0.2 on 2024-06-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0020_alter_badge_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roster.duty')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roster.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roster.member')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roster.status')),
            ],
        ),
    ]
