# Generated by Django 5.0.2 on 2024-08-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0021_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.duty'),
        ),
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.event'),
        ),
        migrations.AlterField(
            model_name='history',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.member'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.status'),
        ),
    ]
