# Generated by Django 5.0.2 on 2025-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0022_alter_history_duty_alter_history_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicekiosk',
            name='allow_duty_selection',
            field=models.BooleanField(default=False, help_text='Allows the selection of a Duty if in Self Service Mode (Automated Checkin False, Single State False).'),
        ),
        migrations.AlterField(
            model_name='servicekiosk',
            name='allow_status_selection',
            field=models.BooleanField(default=False, help_text='Allows the selection of a Status if in Self Service Mode (Automated Checkin False, Single State False).'),
        ),
        migrations.AlterField(
            model_name='servicekiosk',
            name='automated_check_in_out',
            field=models.BooleanField(default=False, help_text='Puts Kiosk into Automated Mode. If Single State is False, will display Check-In and Check-Out automations. If Single State is True, will Display only Check-In automation.'),
        ),
    ]
