# Generated by Django 5.0.2 on 2026-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0023_alter_servicekiosk_allow_duty_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='codes',
            field=models.JSONField(default=dict, help_text='Codes for Calls in format [key, name, color]'),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_mesh',
            field=models.BooleanField(default=False, help_text='Enables the feature to mesh radios'),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_mesh_api_base',
            field=models.CharField(blank=True, help_text='Base URL for Mesh API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_mesh_api_key',
            field=models.CharField(blank=True, help_text='API Key for Mesh API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_mesh_channel',
            field=models.IntegerField(blank=True, default=0, help_text='Channel ID for Mesh API', null=True),
        ),
    ]
